#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

# Add the special clang flags and RUSTFLAGS.
eval "$($MOZSEARCH_PATH/scripts/indexer-setup.py)"

pushd "$FILES_ROOT"

./mach bootstrap-gstreamer
./mach cargo check -p servo

popd

date
