#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

echo Downloading Servo
pushd $INDEX_ROOT
if [ -d "servo" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    git clone https://github.com/servo/servo servo
fi
popd

date

echo Downloading Servo blame
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found existing blame folder; skipping re-download."
else
    git init blame
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git pull
popd

echo Generating blame information
python $MOZSEARCH_PATH/blame/transform-repo.py $GIT_ROOT $BLAME_ROOT

date
